# Generated by Django 4.2.17 on 2024-12-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0002_alter_recipe_description_alter_recipe_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=30, help_text='Cooking time in minutes'),
        ),
    ]
