# Generated by Django 4.2.17 on 2024-12-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0003_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['status', '-updated_on']},
        ),
    ]
