# Generated by Django 4.2.17 on 2024-12-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0004_alter_recipe_options'),
        ('christmas', '0005_remove_recipe_favorites_recipe_favourites'),
    ]

    operations = [
    ]
