# Generated by Django 4.2.17 on 2024-12-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0006_merge_20241214_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Main', 'Main'), ('Side', 'Side'), ('Dessert', 'Dessert')], default='Main', max_length=10),
        ),
    ]
